# tensor basic test

## Tensor reset
- torch.tensor
- torch.from_numpy: 원본 데이터와 메모리 공유

In [1]:
import torch
import numpy as np

#텐서 초기화 하기 위해 데이터로 부터 텐서 생성
#데이터의 자료형(data type)은 자동으로 유추
data = [[1,2],[3,4]]    #list

#list -> tensor
x_data = torch.tensor(data)
print(x_data,'\n', type(data),'->',type(x_data))


#array -> tensor
np_array = np.array(data)   #list -> array
x_np = torch.from_numpy(np_array)   
print(x_np,'\n', type(np_array),'->',type(x_np))



tensor([[1, 2],
        [3, 4]]) 
 <class 'list'> -> <class 'torch.Tensor'>
tensor([[1, 2],
        [3, 4]], dtype=torch.int32) 
 <class 'numpy.ndarray'> -> <class 'torch.Tensor'>


In [2]:
# NumPy 배열 생성
np_array = np.array([1, 2, 3])


# torch.tensor()를 사용하여 NumPy 배열을 Tensor로 변환
tensor_1 = torch.tensor(np_array)
print(type(tensor_1))

# torch.from_numpy()를 사용하여 NumPy 배열을 Tensor로 변환
tensor_2 = torch.from_numpy(np_array)
print(type(tensor_2))

# NumPy 배열과 Tensor의 데이터 변경
np_array[0] = 5
tensor_1[1] = 10

print(np_array)     # 출력: [5 2 3]
print(tensor_1)     # 출력: tensor([ 1, 10,  3])
print(tensor_2)     # 출력: tensor([5, 2, 3])

<class 'torch.Tensor'>
<class 'torch.Tensor'>
[5 2 3]
tensor([ 1, 10,  3], dtype=torch.int32)
tensor([5, 2, 3], dtype=torch.int32)


****torch.from_numpy는 원본 데이터의 메모리를 공유한다

In [75]:
###################
#같은 메모리 공간 할당받음
t = torch.ones(5,)

print(t)
n = t.numpy()
print(n)

t.add_(1)     #add_사용!!
print(t)
print(n)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


****torch -> numpy (.numpy)는 같은 메모리 할당받는다!!!!

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

- torch.ones_like: 1로 이루어진 텐서
- torch.rand_like: 랜럼 텐서 

In [14]:
#다른 텐서로부터 생성
#명시적 override를 하지 않으면, 인자로 주어진 텐서

#ones_like : 원본 데이터 속성 유지
x_ones = torch.ones_like(x_data)
print(f"ones Tensor: \n{x_ones} \n", type(x_ones))

#
x_rand = torch.rand_like(x_data, dtype=torch.float)   #왜 int는 안되는지?
print(f"Random Tensor: \n {x_rand}\n", type(x_rand))

ones Tensor: 
tensor([[1, 1],
        [1, 1]]) 
 <class 'torch.Tensor'>
Random Tensor: 
 tensor([[0.5507, 0.5637],
        [0.7980, 0.6003]])
 <class 'torch.Tensor'>


In [45]:
#shape에 맞는 tensor 만들기

shape =(2,3,4)
rand_tensor = torch.rand(shape)*5 #0-1사이 값이므로 *5로 해주므로 0-5사이 값
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"random: {rand_tensor}")
print(f"ones :{ones_tensor}")
print(f"Zeros :{zeros_tensor}")

random: tensor([[[3.0802, 3.4839, 4.5183, 2.2850],
         [4.9942, 2.4169, 0.9382, 1.1430],
         [4.6767, 2.2364, 3.9461, 3.9746]],

        [[1.1779, 2.3117, 1.7415, 2.9319],
         [1.0926, 1.6039, 1.0690, 3.9527],
         [0.5787, 1.9033, 1.7045, 2.6688]]])
ones :tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
Zeros :tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [22]:
#유효 범위 주어지기
shape_temp = (3,4,)
min_val = 6
max_val =10
rand_tensor_temp = torch.rand(shape_temp) *(max_val - min_val) + min_val
print(f"rnad tensor: {rand_tensor_temp}")

rnad tensor: tensor([[7.3285, 8.6496, 6.5455, 6.4652],
        [7.7215, 8.7615, 9.3290, 7.0596],
        [7.5997, 8.4116, 6.5132, 8.4224]])


## Tensor 속성

In [25]:
tensor_val = torch.rand(3,4)
print(tensor_val)
print(type(tensor_val))
print(tensor_val.shape)
print(tensor_val.device) #device확인

tensor([[0.9901, 0.0682, 0.1157, 0.7901],
        [0.3635, 0.1632, 0.3571, 0.6390],
        [0.2862, 0.5881, 0.3947, 0.2890]])
<class 'torch.Tensor'>
torch.Size([3, 4])
cpu


In [28]:
#device 정보 가져오기
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)

#cuda로 바꿀때
#tensor_val.to('cuda')


cpu


## 슬라이싱

### tensor 값 바꾸기

In [29]:
tensor_val

tensor([[0.9901, 0.0682, 0.1157, 0.7901],
        [0.3635, 0.1632, 0.3571, 0.6390],
        [0.2862, 0.5881, 0.3947, 0.2890]])

In [31]:
tensor_val[:,1]=0
print(tensor_val)

tensor([[0.9901, 0.0000, 0.1157, 0.7901],
        [0.3635, 0.0000, 0.3571, 0.6390],
        [0.2862, 0.0000, 0.3947, 0.2890]])


In [46]:
rand_tensor

tensor([[[3.0802, 3.4839, 4.5183, 2.2850],
         [4.9942, 2.4169, 0.9382, 1.1430],
         [4.6767, 2.2364, 3.9461, 3.9746]],

        [[1.1779, 2.3117, 1.7415, 2.9319],
         [1.0926, 1.6039, 1.0690, 3.9527],
         [0.5787, 1.9033, 1.7045, 2.6688]]])

In [47]:
rand_tensor[:,:,2]=0
print(rand_tensor)

tensor([[[3.0802, 3.4839, 0.0000, 2.2850],
         [4.9942, 2.4169, 0.0000, 1.1430],
         [4.6767, 2.2364, 0.0000, 3.9746]],

        [[1.1779, 2.3117, 0.0000, 2.9319],
         [1.0926, 1.6039, 0.0000, 3.9527],
         [0.5787, 1.9033, 0.0000, 2.6688]]])


### 합치기

In [50]:
print(tensor_val)
print(rand_tensor_temp)

tensor([[0.9901, 0.0000, 0.1157, 0.7901],
        [0.3635, 0.0000, 0.3571, 0.6390],
        [0.2862, 0.0000, 0.3947, 0.2890]])
tensor([[7.3285, 8.6496, 6.5455, 6.4652],
        [7.7215, 8.7615, 9.3290, 7.0596],
        [7.5997, 8.4116, 6.5132, 8.4224]])


In [57]:
t1 = torch.cat([tensor_val, rand_tensor_temp], dim=0)
t2 = torch.cat([tensor_val, rand_tensor_temp], dim=1)
print(t1, t1.shape)
print(t2, t2.shape)


tensor([[0.9901, 0.0000, 0.1157, 0.7901],
        [0.3635, 0.0000, 0.3571, 0.6390],
        [0.2862, 0.0000, 0.3947, 0.2890],
        [7.3285, 8.6496, 6.5455, 6.4652],
        [7.7215, 8.7615, 9.3290, 7.0596],
        [7.5997, 8.4116, 6.5132, 8.4224]]) torch.Size([6, 4])
tensor([[0.9901, 0.0000, 0.1157, 0.7901, 7.3285, 8.6496, 6.5455, 6.4652],
        [0.3635, 0.0000, 0.3571, 0.6390, 7.7215, 8.7615, 9.3290, 7.0596],
        [0.2862, 0.0000, 0.3947, 0.2890, 7.5997, 8.4116, 6.5132, 8.4224]]) torch.Size([3, 8])


### 곱하기

In [67]:
two_tensor = ones_tensor *2
print(two_tensor)
print(tensor_val)

t_mul = tensor_val.mul(two_tensor)
print(t_mul)
#print(tensor_val * two_tensor)



tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]],

        [[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])
tensor([[0.9901, 0.0000, 0.1157, 0.7901],
        [0.3635, 0.0000, 0.3571, 0.6390],
        [0.2862, 0.0000, 0.3947, 0.2890]])
tensor([[[1.9801, 0.0000, 0.2314, 1.5802],
         [0.7270, 0.0000, 0.7141, 1.2780],
         [0.5724, 0.0000, 0.7894, 0.5780]],

        [[1.9801, 0.0000, 0.2314, 1.5802],
         [0.7270, 0.0000, 0.7141, 1.2780],
         [0.5724, 0.0000, 0.7894, 0.5780]]])


In [71]:
tree_tensor = torch.ones(3,4) *3
print(tensor_val.T)
print(tree_tensor)
print(tree_tensor@tensor_val.T)         #같은 크기만 가능

tensor([[0.9901, 0.3635, 0.2862],
        [0.0000, 0.0000, 0.0000],
        [0.1157, 0.3571, 0.3947],
        [0.7901, 0.6390, 0.2890]])
tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]])
tensor([[5.6876, 4.0787, 2.9098],
        [5.6876, 4.0787, 2.9098],
        [5.6876, 4.0787, 2.9098]])


## Tensor 크기변경 

### View
***중요: 원소의 수 유지하면서 텐서 크기 변경

np.reshape과 같은 역할/

In [89]:
t = np.array([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
ft = torch.FloatTensor(t)
print(ft, ft.shape)

tensor([[[ 0.,  1.,  2.],
         [ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.],
         [ 9., 10., 11.]]]) torch.Size([2, 2, 3])


In [91]:
"""
[2,2,3]으로 원소의 수는 12개
-> [4,3]으로 원소의 수 동일하게 12개
tensor의 크기만 변경
"""

view_ft = ft.view([-1,1,3])     #-1:알아서 맞춰줘 (?,1,3)의 크기로
#view_ft = ft.view([4,3]) 
print(view_ft)
print(view_ft.shape)

print(ft.view([-1,3]))
print(ft.view([-1,3]).shape)

tensor([[[ 0.,  1.,  2.]],

        [[ 3.,  4.,  5.]],

        [[ 6.,  7.,  8.]],

        [[ 9., 10., 11.]]])
torch.Size([4, 1, 3])
tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])
torch.Size([4, 3])


### Squeeze 스퀴즈/ unsqueeze
스퀴즈: 1인 차원 제거

In [96]:
one_t = torch.ones(2,2,1)
print(one_t, one_t.shape)
"""
[2,2,1] ->[2,2]
1인 차원을 제거 
"""

print(one_t.squeeze(), one_t.squeeze().shape)

tensor([[[1.],
         [1.]],

        [[1.],
         [1.]]]) torch.Size([2, 2, 1])
tensor([[1., 1.],
        [1., 1.]]) torch.Size([2, 2])


In [108]:
# 그럼 (1,3)이면?
one_t_ = torch.ones(1,3)
print(one_t_, one_t_.shape)
print(one_t_.squeeze(),one_t_.squeeze().shape)

#view로 표현
print(one_t_.view(3), one_t_.view(3).shape)

tensor([[1., 1., 1.]]) torch.Size([1, 3])
tensor([1., 1., 1.]) torch.Size([3])
tensor([1., 1., 1.]) torch.Size([3])


: 

unsqueeze: 1차원 추가

In [107]:
print(one_t_, one_t_.shape)
print(one_t_.unsqueeze(0), one_t_.unsqueeze(0).shape)


#view로 표현하기
print(one_t_.view(1,-1,3), one_t_.view(1,-1,3).shape)

tensor([[1., 1., 1.]]) torch.Size([1, 3])
tensor([[[1., 1., 1.]]]) torch.Size([1, 1, 3])
tensor([[[1., 1., 1.]]]) torch.Size([1, 1, 3])


## Type casting